image: node:latest
cache:
  paths:
  - node_modules/
pages:
  stage: deploy
  script:
  - npm install
  - npm install @angular/cli
  - npm install @angular/compiler-cli
  - npm run build-pub
  artifacts:
    paths:
    - public